# Generated by Django 6.0.6 on 2026-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=200)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Electric', 'Electric')], db_index=True, max_length=20)),
                ('kms_driven', models.IntegerField()),
                ('engine_capacity_cc', models.IntegerField(default=0)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-year', 'brand', 'bike_name'],
            },
        ),
    ]
